### ISSUE TITLE
Some games lock the cursor, which makes pointless the current mouse tracking

### ISSUE THREAD

**Issue by AndyLobjois** [flamestream/input-device-emitter#3]
_[I've already posted this message on the SteamWorkshop page of the plugin]_

Hey, great plugin, thanks a lot !
There is an annoying issue about mouse tracking: Some games lock the cursor in the center of the screen, which makes pointless the mouse tracking !

I've tried to implement/test Raw Mouse position but I don't know C++, even by following MS documentation about [WM_INPUT](https://learn.microsoft.com/en-us/windows/win32/dxtecharts/taking-advantage-of-high-dpi-mouse-movement) but I can't figure out how to implement it correctly :/
I'm embarassed to ask but are you interested to implement this feature in your plugin ?

Thanks again for the plugin !

**Comment by flamestream** [comment]
Hello there. Reaching out here is all good, since I don't get to receive any notifications from Steam.

That is correct, many games will move the mouse cursor back to the middle of the screen for their purpose and therefore, the tracking will repeatedly report it to be staying there. The raw signal is effectively tracking correctly. 

You may have something in mind in terms of different tracking behavior against that situation. Can you share exactly what it is that is wanted? I can maybe provide some insight on its feasibility

**Comment by AndyLobjois** [comment]
First of all, be aware I'm a hacky dev with no correct dev background, so my solutions are always wanky haha
I've already tackle this issue in a previous project thanks to an AutoHotKey script for getting the Delta of the mouse.

My process was to get mouse delta (vector2) and increment it everytime (a bit like velocity ?), so the mouse position is not correct but at least the mouse isn't locked in place !

Here is the code I use for getting mouse delta with AHK (AHK use it's own language):
```Js
Class MouseDelta {
    State := 0
    DevSize := 8 + A_PtrSize
    devMult := 1
    LastError := 0
    RAWINPUTDEVICE := Buffer(this.DevSize * this.devMult)
    
    __New(callback) {
        this.MouseMovedFn := ObjBindMethod(this,"MouseMoved")
        , this.Callback := callback
    }

    Start() {
        Static RIDEV_INPUTSINK := 0x00000100 ; Register mouse for WM_INPUT messages.
        
        NumPut("UShort",1,"UShort",2,"UInt",RIDEV_INPUTSINK,"UPtr", A_ScriptHwnd, this.RAWINPUTDEVICE.ptr) //populate RAWINPUTDEVICE
        
        result := DllCall("RegisterRawInputDevices", "UPtr", this.RAWINPUTDEVICE.Ptr, "UInt", this.devMult, "UInt", this.DevSize )
        this.LastError := A_LastError
        
        OnMessage(0x00FF, this.MouseMovedFn)
        this.State := 1
        return this    // allow chaining
    }
    
    Stop() {
        static RIDEV_REMOVE := 0x00000001
        OnMessage(0x00FF, this.MouseMovedFn, 0)
        
        NumPut("UInt", RIDEV_REMOVE, "UPtr", 0, this.RAWINPUTDEVICE, 4)
        
        DllCall("RegisterRawInputDevices", "UPtr", this.RAWINPUTDEVICE.Ptr, "UInt", this.devMult, "UInt", this.DevSize)
        this.LastError := A_LastError
        
        this.State := 0
        return this    // allow chaining
    }
    
    SetState(state) {
        if (state && !this.State)
            this.Start()
        else if (!state && this.State)
            this.Stop()
        return this    // allow chaining
    }

    Delete() {
        this.Stop()
        this.MouseMovedFn := ""
    }
    
    MouseMoved(wParam, lParam, msg, hwnd) { // Called when the mouse moved and get raw input stats.
        Critical
        Static headerSz   := 2 * A_PtrSize
        Static pcbSize    := 8 + headerSz
        Static uRawInput  := {ptr:0}, structSize := 0
        
        header := Buffer(pcbSize, 0) // Get hDevice from RAWINPUTHEADER to identify which mouse this data came from
        If !DllCall("GetRawInputData", "UPtr", lParam, "uint", 0x10000005
                                     , "UPtr", header.ptr, "Uint*", &pcbSize, "Uint", pcbSize) {
            this.LastError := A_LastError
            Return 0
        }
        
        hwID := NumGet(header, 8, "UPtr")
        
        If !structSize
            structSize := NumGet(header, 4, "UInt")
          , uRawInput := Buffer(structSize)
        
        r := DllCall("GetRawInputData", "UInt", lParam, "UInt", 0x10000003               // Get RawInput data
                                      , "UPtr", uRawInput.ptr, "UInt*", &structSize, "UInt", 8 + headerSz)
        this.LastError := A_LastError
        
        Static mFlags_off   := 12+headerSz, mData_off := 14+headerSz
             , mXd_off      := 20+headerSz, mYd_off   := 24+headerSz
             , mExtra_off   := 28+headerSz
        Static b1 := 0, b2 := 0, b3 := 0, b4 := 0, b5 := 0, mw := 0
        
        flags := NumGet(uRawInput, mFlags_off, "UShort")    // +12
        data  := NumGet(uRawInput, mData_off, "Short")      // +14
        
        (flags & 0x1)   ? b1 := true : (flags & 0x2)   ? b1 := false : ""
        (flags & 0x4)   ? b2 := true : (flags & 0x8)   ? b2 := false : ""
        (flags & 0x10)  ? b3 := true : (flags & 0x20)  ? b3 := false : ""
        (flags & 0x40)  ? b4 := true : (flags & 0x80)  ? b4 := false : ""
        (flags & 0x100) ? b5 := true : (flags & 0x200) ? b5 := false : ""
        (flags & 0x400) ? (mw := data) : (mw := 0) // mouse wheel delta
        
        xD := NumGet(uRawInput, mXd_off, "Int") // x Delta
        yD := NumGet(uRawInput, mYd_off, "Int") // y Delta
        
        POINT := Buffer(8,0)
        DllCall("GetCursorPos","UPtr",POINT.ptr)
        x := NumGet(POINT,"UInt")
        y := NumGet(POINT,4,"UInt")
        
        obj := {x:x, y:y, xD:xD, yD:yD
              , b1:b1, b2:b2, b3:b3, b4:b4, b5:b5, mw:mw}
        
        Critical false
        this.callback(hwID, obj)
    }
}
```

It looks like the WM_INPUT thing from MS documentation.

I write obj.xD and obj.yD values in a .txt file and Unity will read it (told you I'm hacky haha)
Then I use these values this way in my Unity C# project :
```Csharp
public void TrackingFromDeltaCursor() {
    Vector2 adjust = new Vector2(width.Float, height.Float);
    Vector2 offset = area * 0.5f;

    // Delta Deadzone (I don't remember why I created a deadzone)
    if (Vector2.Distance(Vector2.zero, inputReader.mouseDeltaPosition) >= 3) {
        delta += inputReader.mouseDeltaPosition; // InputReader is my script that read my dirty .txt files
        delta = new Vector2(
            Mathf.Clamp(delta.x, 0, screen.x),
            Mathf.Clamp(delta.y, 0, screen.y));
    }

    // Apply (cursor is a vector3 running in an Update loop)
    cursor = (delta / screen * area * adjust - offset);
```

I hopes it's not too confusing !

**Comment by flamestream** [comment]
Ah okay, so you want to simulate pointer moving on the screen based on delta, despite it not really moving away from the center.
That's interesting. I'm guessing that you don't mind that it stays at some edge of the screen for a bit since the position is always calculated and not absolutely set?

**Comment by AndyLobjois** [comment]
I don't mind indeed, the only matter is the character move hand even with cursor lock.
Also the clamping should help ? I don't know if the raw mouse position is calculated in pixels but with screen clamping, it's only an issue when you always move the mouse in the same direction.

OR instead of clamping, the cursor go back to center everytime the value exceed the screen resolution ?
So the character kinda simulate the behaviour of flicking the mouse several times
![flick-mouse](https://github.com/flamestream/input-device-emitter/assets/74135989/255f65f4-108c-4777-8902-e163e615ed2f)

Anyway, if you have a better idea go ahead, if you are akin to do it of course !
(Looking back to the MS documentation, I think my mistake lays around device registration ... C++ isn't as scary after all !)

**Comment by flamestream** [comment]
All good. I just wanted to understand the use-case. I now see the appeal of seeing the character do mouse movement as you are playing games that lock the cursor.
Your shared approach is overall good and pretty much the only way to handle this situation.
I'll see how it can be incorporated in the plug-in.

**Comment by flamestream** [comment]
Support has been implemented in the plug-in in the latest release.
It has minimal configuration for now but it should work for typical FPS games.
https://github.com/flamestream/warudo-input-receiver/releases/tag/v3.4.0

**Comment by AndyLobjois** [comment]
Thanks !
The warudo plugin (FS Input Receiver) is updated but the FS Input Emitter isn't updated, right ?
Or am I missing something ?

**Comment by flamestream** [comment]
Correct. The emitter stays the same as its purpose is to emit raw signals. The cursor pinning is not an incorrect behaviour, but rather the result of an override made by another application; the tracked coordinates are therefore accurate still.
