### ISSUE TITLE
Allow user to choose the device index for gamepad emitter

### ISSUE THREAD

**Issue by AndyLobjois** [flamestream/input-device-emitter#5]
When you have several devices connected, it's kinda annoying to disconnect/reconnect for getting the correct order.

Of course a Warudo UI integration could be awesome but an additional argument like `--gamepad-index 4` (target the 4th device in the list) should do the job perfectly.

Edit: I read back the "Limitations" text and looks like it's not that easy
> Only one gamepad is supported. The first one detected will be hooked to

Is this possible to detect the last gamepad hooked instead ? So the user only have to disconnect/connect.

Thanks again for your great work 🙏

**Comment by flamestream** [comment]
Oh, I was sure I added that in a previous version.
https://github.com/flamestream/input-device-emitter/releases/tag/v1.1
Is that flag not working in the latest one?
(That said, I should update that outdated readme note...)

**Comment by AndyLobjois** [comment]
Ooooh my bad ! I haven't read carefully the --help, sorry !
